// @ts-nocheck
"use client";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Eraser, Trash2, ChevronRight, Trophy } from "lucide-react";

const WORDS=["Jollof Rice","Danfo Bus","Lagos Traffic","Suya","Agbada","Ankara","Harmattan","Generator","Naira","Okada","Afrobeats","Nollywood","Bode Market","Third Mainland Bridge","Aso Rock","Pepper Soup","Egusi","Pounded Yam","Chin Chin","Pure Water","Yellow Bus","Fuel Queue","NEPA","Football","Basketball","Highlife","Drum","Microphone","Stage","Audience"];
const COLORS_PALETTE=["#000000","#ffffff","#ef4444","#f97316","#eab308","#22c55e","#3b82f6","#8b5cf6","#ec4899","#78716c","#6b7280","#d97706","#065f46","#1e40af","#7c3aed","#be185d"];
const BRUSH_SIZES=[2,5,10,20];
const PLAYERS=[{id:"you",name:"You",avatar:"😎"},{id:"b1",name:"Lagos King",avatar:"👑"},{id:"b2",name:"Abuja Babe",avatar:"💅"},{id:"b3",name:"PH G",avatar:"🔥"}];
const GUESSES_FOR_WORD={"Jollof Rice":["jollof","rice","food","naija food","jollof rice"],"Danfo Bus":["bus","danfo","yellow bus","transport"],"Lagos Traffic":["traffic","hold up","jam","lagos"],Suya:["suya","meat","bbq","grilled"],Afrobeats:["music","afrobeats","beats","naija music"]};

export default function DrawingPage(){
 const canvasRef=useRef<HTMLCanvasElement>(null); const lastPos=useRef<any>(null);
 const [drawing,setDrawing]=useState(false),[color,setColor]=useState("#000000"),[brushSize,setBrushSize]=useState(5),[erasing,setErasing]=useState(false),[word,setWord]=useState(""),[timeLeft,setTimeLeft]=useState(60),[round,setRound]=useState(1),[phase,setPhase]=useState("lobby"),[guess,setGuess]=useState(""),[guesses,setGuesses]=useState<any[]>([]),[scores,setScores]=useState([0,0,0,0]),[drawer,setDrawer]=useState(0),[message,setMessage]=useState("");
 const ctx=()=>canvasRef.current?.getContext("2d");
 const clearCanvas=()=>{const c=canvasRef.current,x=ctx();if(!c||!x)return;x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height)};
 useEffect(()=>{clearCanvas()},[]); useEffect(()=>{if(phase!=="drawing"&&phase!=="guessing")return;if(timeLeft<=0){setPhase("reveal");return}const t=setTimeout(()=>setTimeLeft(v=>v-1),1000);return()=>clearTimeout(t)},[timeLeft,phase]);
 const getPos=(e:any,c:any)=>{const r=c.getBoundingClientRect(),sx=c.width/r.width,sy=c.height/r.height;const p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*sx,y:(p.clientY-r.top)*sy}};
 const startDraw=(e:any)=>{if(!canvasRef.current||drawer!==0)return;e.preventDefault();setDrawing(true);lastPos.current=getPos(e,canvasRef.current)};
 const draw=(e:any)=>{if(!drawing||!canvasRef.current||drawer!==0)return;e.preventDefault();const x=ctx();if(!x)return;const p=getPos(e,canvasRef.current);if(!lastPos.current){lastPos.current=p;return}x.beginPath();x.moveTo(lastPos.current.x,lastPos.current.y);x.lineTo(p.x,p.y);x.strokeStyle=erasing?"#fff":color;x.lineWidth=brushSize;x.lineCap="round";x.lineJoin="round";x.stroke();lastPos.current=p};
 const stopDraw=(e?:any)=>{e?.preventDefault();setDrawing(false);lastPos.current=null};
 const startRound=()=>{const w=WORDS[Math.floor(Math.random()*WORDS.length)];setWord(w);setTimeLeft(60);setGuesses([]);setMessage("");setPhase("drawing");setDrawer(0);clearCanvas()};
 const submitGuess=()=>{if(!guess.trim())return;const correct=(GUESSES_FOR_WORD[word]||[word.toLowerCase()]).some((g:string)=>guess.toLowerCase().includes(g));setGuesses(v=>[...v,{player:"You",text:guess,correct}]);if(correct){setScores(v=>{const n=[...v];n[0]+=150;return n});setMessage("You got it! 🎉 +150 pts")};setGuess("")};
 return <div className="min-h-screen bg-[#0a0a0a] overscroll-none" style={{touchAction:"pan-y"}}><main className="max-w-4xl mx-auto px-3 py-3">
  <div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Link href="/games" className="text-zinc-500 hover:text-white text-xs">← Play</Link><h1 className="text-xl font-black text-white">Draw Am 🎨</h1></div>{phase!=="lobby"&&<div className={`px-2.5 py-1 rounded-full text-xs font-black ${timeLeft<=10?"bg-red-500 text-white animate-pulse":"bg-zinc-800 text-white"}`}>⏱ {timeLeft}s</div>}</div>
  {phase==="lobby"&&<div className="bg-zinc-950 border border-zinc-800 rounded-2xl p-5 text-center"><div className="text-4xl mb-2">🎨</div><h2 className="text-white font-black text-xl mb-1">Draw Am</h2><div className="flex justify-center gap-4 mb-5">{PLAYERS.map((p,i)=><div key={p.id} className="text-center"><div className="text-xl">{p.avatar}</div><div className="text-white text-[11px] font-bold">{p.name}</div><div className="text-yellow-400 text-[10px]">{scores[i]} pts</div></div>)}</div><button onClick={startRound} className="bg-yellow-400 text-black font-black px-6 py-2.5 rounded-full text-sm">Start Drawing 🎨</button></div>}
  {(phase==="drawing"||phase==="guessing")&&<div className="grid grid-cols-1 md:grid-cols-3 gap-3">
   <div className="md:col-span-2 space-y-2"><div className="bg-zinc-950 border border-zinc-800 rounded-xl p-2 text-center">{drawer===0?<><span className="text-zinc-400 text-[10px]">DRAW THIS: </span><span className="text-yellow-400 font-black text-base">{word}</span></>:<span className="text-white font-black text-base">GUESS</span>}</div>
    <div className="bg-white rounded-2xl overflow-hidden border-2 border-zinc-700 select-none"><canvas ref={canvasRef} width={600} height={400} className="w-full block touch-none cursor-crosshair" style={{touchAction:"none"}} onMouseDown={startDraw} onMouseMove={draw} onMouseUp={stopDraw} onMouseLeave={stopDraw} onTouchStart={startDraw} onTouchMove={draw} onTouchEnd={stopDraw} onTouchCancel={stopDraw}/></div>
    {drawer===0&&<div className="bg-zinc-950 border border-zinc-800 rounded-xl p-2 flex flex-wrap items-center gap-2">{COLORS_PALETTE.map(c=><button key={c} onClick={()=>{setColor(c);setErasing(false)}} aria-label="color" className={`w-5 h-5 rounded-full border ${color===c&&!erasing?"border-white scale-125":"border-transparent"}`} style={{backgroundColor:c}}/>)}<div className="w-px h-5 bg-zinc-700"/>{BRUSH_SIZES.map(s=><button key={s} onClick={()=>{setBrushSize(s);setErasing(false)}} className={`w-7 h-7 bg-zinc-800 rounded-lg flex items-center justify-center ${brushSize===s&&!erasing?"border border-yellow-400":""}`}><div className="bg-white rounded-full" style={{width:Math.min(s,16),height:Math.min(s,16)}}/></button>)}<button onClick={()=>setErasing(!erasing)} className={`flex items-center gap-1 px-2 py-1.5 rounded-lg text-[10px] font-bold ${erasing?"bg-yellow-400 text-black":"bg-zinc-800 text-zinc-300"}`}><Eraser size={13}/>Erase</button><button onClick={clearCanvas} className="p-1.5 rounded-lg bg-zinc-800 text-zinc-300"><Trash2 size={13}/></button></div>}
    {drawer!==0&&<div className="flex gap-2"><input value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submitGuess()} placeholder="Guess it…" className="flex-1 bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2 text-sm text-white"/><button onClick={submitGuess} className="bg-yellow-400 text-black font-black px-4 rounded-xl text-sm">Guess</button></div>}
    {message&&<div className="text-center text-yellow-400 text-sm font-bold">{message}</div>}</div>
   <aside className="bg-zinc-950 border border-zinc-800 rounded-xl p-3"><div className="text-white font-black text-sm mb-2">Guesses</div><div className="space-y-1.5 max-h-56 overflow-y-auto">{guesses.length?guesses.map((g,i)=><div key={i} className={`text-xs p-2 rounded-lg ${g.correct?"bg-emerald-500/10 text-emerald-300":"bg-zinc-900 text-zinc-300"}`}><b>{g.player}:</b> {g.text}</div>):<div className="text-zinc-600 text-xs">Guesses appear here.</div>}</div><div className="mt-4 border-t border-zinc-800 pt-3 text-xs text-zinc-400">Round {round}</div></aside>
  </div>}
 </main></div>
}